"""empty message

Revision ID: 1762ba78f222
Revises: d75f6dcebb84
Create Date: 2024-03-28 22:54:17.096355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1762ba78f222"
down_revision = "d75f6dcebb84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column(
            "post_id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=32),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column(
            "post_id",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
