"""empty message

Revision ID: 2385e51c7bee
Revises: c98ed6a42381
Create Date: 2024-04-02 22:13:51.828242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2385e51c7bee"
down_revision = "c98ed6a42381"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tag", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("tag")

    # ### end Alembic commands ###
