"""empty message

Revision ID: 30de26177e3e
Revises: 7424cd8798eb
Create Date: 2024-02-25 13:09:36.828825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30de26177e3e"
down_revision = "7424cd8798eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
