"""empty message

Revision ID: 4e3ef28a7e57
Revises: 0287d96c7276
Create Date: 2024-03-01 20:36:57.663178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e3ef28a7e57"
down_revision = "0287d96c7276"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_id", sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, "post", ["post_id"], ["id"])

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_url", sa.String(length=150), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("post_id")

    # ### end Alembic commands ###
