"""empty message

Revision ID: 70cfca0dec00
Revises: 4e3ef28a7e57
Create Date: 2024-03-24 16:57:10.437387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70cfca0dec00"
down_revision = "4e3ef28a7e57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=21),
            existing_nullable=False,
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=21),
            existing_nullable=False,
        )

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=21),
            existing_nullable=False,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=21),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=21),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=21),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=21),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=21),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
