"""Use uuid

Revision ID: bf73ce933aaa
Revises: 5b4605a3ae36
Create Date: 2024-03-27 22:01:16.840249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf73ce933aaa"
down_revision = "5b4605a3ae36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=32),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_comment_id")
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=32),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_post_id")
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=32),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_role_id")
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=32),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_user_id")
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index("ix_user_id", ["id"], unique=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index("ix_role_id", ["id"], unique=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index("ix_post_id", ["id"], unique=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index("ix_comment_id", ["id"], unique=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
