"""empty message

Revision ID: d75f6dcebb84
Revises: bf73ce933aaa
Create Date: 2024-03-27 22:04:46.041368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d75f6dcebb84"
down_revision = "bf73ce933aaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint("comment_id_key", type_="unique")
        batch_op.create_index(batch_op.f("ix_comment_id"), ["id"], unique=True)

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint("post_id_key", type_="unique")
        batch_op.create_index(batch_op.f("ix_post_id"), ["id"], unique=True)

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_constraint("role_id_key", type_="unique")
        batch_op.create_index(batch_op.f("ix_role_id"), ["id"], unique=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("user_id_key", type_="unique")
        batch_op.create_index(batch_op.f("ix_user_id"), ["id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_id"))
        batch_op.create_unique_constraint("user_id_key", ["id"])

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_id"))
        batch_op.create_unique_constraint("role_id_key", ["id"])

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_id"))
        batch_op.create_unique_constraint("post_id_key", ["id"])

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_id"))
        batch_op.create_unique_constraint("comment_id_key", ["id"])

    # ### end Alembic commands ###
