name: Docker Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH into Server, Pull Changes, and Build Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ${{ secrets.WORK_DIR }}
          git pull origin main
          docker build -t kemistry .
          docker tag kemistry kevinkoech357/kemistry

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker Image
      run: docker push kevinkoech357/kemistry

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker pull kevinkoech357/kemistry
          docker stop kemistry_container || true
          docker rm kemistry_container || true
          docker run -d -p 8007:8007 --name kemistry_container kevinkoech357/kemistry

    - name: Restart Nginx
      run: |
        expect -c '
        spawn ssh $env(SSh_USER)@$env(SSh_HOST) "sudo service nginx restart"
        expect "password:"
        send "${{ secrets.SSH_PASSWORD }}\r"
        expect eof
        '

    - name: Cleanup
      run: rm -f ~/.ssh/id_rsa ~/.ssh/known_hosts
